name: Release
on:
  push:
    tags:
      - "*"
jobs:
  call-release-reusable:
    uses: raju-b71/github-reusable-workflows/.github/workflows/release.yml@main
    with:
      project_name: expense-frontend1
      npm_install: false
      release_archive_file: "*"
    secrets: inherit