name: Release
on:
  push:
    tags:
      - "*"
jobs:
  call-release-reusable:
    uses: raju-b71/github-reusable-workflows/.github/workflows/release.yml@main
    with:
      project-name: expense-frontend
      npm_install: true
      release_archive_file: "*"
    secrets: inherit
#k,lhihhdk